# Generated by Django 3.1.7 on 2021-03-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gltf_buffer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('siteid', models.IntegerField()),
                ('bimid', models.IntegerField()),
                ('buffer', models.JSONField(null=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gltf_buffer2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('siteid', models.IntegerField()),
                ('bimid', models.IntegerField()),
                ('buffer', models.BinaryField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='%m')),
            ],
        ),
        migrations.CreateModel(
            name='Gltf_json',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('siteid', models.IntegerField()),
                ('bimid', models.IntegerField()),
                ('data', models.JSONField(null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='gltf_json',
            constraint=models.UniqueConstraint(fields=('siteid', 'bimid'), name='unique_json_id'),
        ),
        migrations.AddConstraint(
            model_name='gltf_buffer2',
            constraint=models.UniqueConstraint(fields=('siteid', 'bimid', 'name'), name='unique_buffer_id2'),
        ),
        migrations.AddConstraint(
            model_name='gltf_buffer',
            constraint=models.UniqueConstraint(fields=('siteid', 'bimid', 'name'), name='unique_buffer_id'),
        ),
    ]
