# Generated by Django 3.1.7 on 2021-03-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('emd_cd', models.CharField(blank=True, max_length=10, null=True)),
                ('emd_nm', models.CharField(blank=True, max_length=40, null=True)),
                ('emd_eng_nm', models.CharField(blank=True, max_length=40, null=True)),
                ('esri_pk', models.IntegerField(blank=True, null=True)),
                ('shape_area', models.DecimalField(decimal_places=100, max_digits=100)),
                ('shape_len', models.DecimalField(decimal_places=100, max_digits=100)),
                ('geom', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
